extends: airbnb-base
parser: babel-eslint
plugins:
  - babel
  - chai-friendly

env:
  node: true
  es6: true
  mocha: true

globals:
  web3: true
  artifacts: true
  contract: true

rules:
  no-use-before-define: 0
  class-methods-use-this: 0
  import/prefer-default-export: 0
  key-spacing: 0
  no-param-reassign: 0
  no-unused-expressions: 0
  chai-friendly/no-unused-expressions: 2
  max-len:
    - error
    - 100
